name: build:docker

on:
  workflow_call:
    secrets:
      PLANTON_CLOUD_CLIENT_ID:
        required: true
      PLANTON_CLOUD_CLIENT_SECRET:
        required: true
    inputs:
      PLANTON_CLOUD_CLI_ENVIRONMENT:
        required: true
        type: string
      PLANTON_CLOUD_ARTIFACT_STORE_ID:
        required: true
        type: string
      PLANTON_CLOUD_ARTIFACT_STORE_DOCKER_REPO_HOSTNAME:
        required: true
        type: string
      CONTAINER_IMAGE_NAME:
        required: true
        type: string
      container_image_tag:
        required: true
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: docker build
    steps:
      - uses: actions/checkout@v3
      - uses: plantoncloud/gh-action-build-docker@chore/inherenc
        with:
          planton_cloud_cli_environment: ${{ inputs.PLANTON_CLOUD_CLI_ENVIRONMENT }}
          planton_cloud_client_id: ${{ secrets.PLANTON_CLOUD_CLIENT_ID }}
          planton_cloud_client_secret: ${{ secrets.PLANTON_CLOUD_CLIENT_SECRET }}
          planton_cloud_artifact_store_id: ${{ inputs.PLANTON_CLOUD_ARTIFACT_STORE_ID }}
          planton_cloud_artifact_store_docker_repo_hostname: ${{ inputs.PLANTON_CLOUD_ARTIFACT_STORE_DOCKER_REPO_HOSTNAME }}
          container_image_name: ${{ inputs.CONTAINER_IMAGE_NAME }}
          container_image_tag: ${{ inputs.container_image_tag }}
