name: Docker Build and Push
description: Builds a Docker image and pushes it to the specified Docker repository

name: Build Docker Image
description: Builds a Docker image

inputs:
  PLANTON_CLOUD_ARTIFACT_STORE_ID:
    description: 'ID of the Artifact Store on Planton Cloud.'
    required: true
  DOCKER_REPO_HOSTNAME:
    description: 'Hostname of the Docker repository'
    required: true
  CONTAINER_IMAGE_REPO:
    description: 'Repo of the Docker image to be built and pushed.'
    required: true
  CONTAINER_IMAGE_TAG:
    description: 'Tag of the Docker image to be built and pushed.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Fetch Artifact Store Key
      run: |
        echo "fetching artifact writer key from planton cloud service"
        artifact_writer_key_json_file="$(pwd)/artifact-writer-key.json"
        planton artifact-store secrets get-writer-key --output-file $artifact_writer_key_json_file --artifact-store-id inputs.PLANTON_CLOUD_ARTIFACT_STORE_ID
        echo "fetched artifact writer key from planton cloud service"
        echo "ARTIFACT_WRITE_KEY_JSON_FILE_PATH=$artifact_writer_key_json_file" >> $GITHUB_ENV
      shell: bash

    - name: Docker Login
      run: |
        ARTIFACT_WRITE_KEY_JSON=env.ARTIFACT_WRITE_KEY_JSON_FILE_PATH
        echo $ARTIFACT_WRITE_KEY_JSON | docker login -u _json_key --password-stdin https://inputs.DOCKER_REPO_HOSTNAME
      shell: bash

    - name: Docker Build
      run: |
        echo "building container image"
        export CONTAINER_IMAGE_REFERENCE=inputs.CONTAINER_IMAGE_REPO:inputs.CONTAINER_IMAGE_TAG
        docker build -t $CONTAINER_IMAGE_REFERENCE .
        echo "built container image"
      shell: bash

    - name: Docker Push
      run: |
        echo "pushing container image"
        export CONTAINER_IMAGE_REFERENCE=inputs.CONTAINER_IMAGE_REPO:inputs.CONTAINER_IMAGE_TAG
        docker push $CONTAINER_IMAGE_REFERENCE
      shell: bash
